### ISSUE TITLE
Consider remove ontology definitions from pipeline representation serialization

### ISSUE THREAD

**Issue by hunterhector** [asyml/forte#584]
**Is your feature request related to a problem? Please describe.**
The current ontology serialized IR looks like the following:

```
components:
- configs:
    serialize_method: jsonpickle
    zip_pack: false
  type: forte.data.readers.string_reader.StringReader
- configs:
    overwrite: false
    user_input: bye
  selector:
    configs: {}
    type: forte.data.selector.DummySelector
  type: advanced_pipeline_test.UserSimulator
forte_ir_version: 0.0.1
states:
  attribute:
    _check_type_consistency: true
    _do_init_type_check: true
    _enable_profiling: true
    _initialized: true
  resource:
    merged_entry_tree:
      attributes: []
      children:
      - attributes: []
        children:
        - attributes:
          - lemma
          - ud_features
          - is_root
          - pos
          children: []
          name: ft.onto.base_ontology.Token
        - attributes: []
          children: []
          name: ft.onto.base_ontology.Document
        - attributes:
```
The `merged_entry_tree` section is quite long and may not really be necessary. Especially if we are able to infer the ontology tree via https://github.com/asyml/forte/issues/583, we can drop this section and make the IR to be more focused on its main objectives.

**Describe the solution you'd like**
After we finish https://github.com/asyml/forte/issues/583, during the pipeline [save](https://github.com/asyml/forte/blob/master/forte/pipeline.py#L324) function, we should drop this [part](https://github.com/asyml/forte/blob/master/forte/pipeline.py#L436). Then we should make sure the [init_from_config](https://github.com/asyml/forte/blob/master/forte/pipeline.py#L313) works correctly with this new change.

**Describe alternatives you've considered**

**Additional context**
